
# ----- Tilting Laser -----
tilt_laser:
  laser_cb_detector_config:  /narrow_stereo/left/cb_detector

  configs:
  - config_name: small_cb_6x8
    laser_cb_detector:
      active: True
      num_x: 6
      num_y: 8
      width_scaling: 1
      height_scaling: 1
      subpixel_window: 4
      subpixel_zero_zone: 1
      flip_horizontal: 1
  - config_name: small_cb_4x5
    laser_cb_detector:
      active: True
      num_x: 6
      num_y: 8
      width_scaling: 1
      height_scaling: 1
      subpixel_window: 4
      subpixel_zero_zone: 1
      flip_horizontal: 1

tilt_laser_6x8:
  laser_cb_detector_config:  /none
  configs: []
